// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvyxfgjvdrwhvczxyoye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eXhmZ2p2ZHJ3aHZjenh5b3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTg5MTEsImV4cCI6MjA2NTQ5NDkxMX0.PBMJlJAZyLLEz4LKzWu-2R33WH4CTYpCxyjcGkOjgGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);